/**
 * Education option lists for the tutor "About you" screen (TutorAbout).
 *
 * These power the searchable dropdowns for university / secondary-school names,
 * the qualification picker, and the per-qualification score scales. All lists
 * are kept in their given order (HK institutions first for universities), and
 * every picker also allows a free-typed value when a school isn't listed.
 *
 * English-only CONTENT (school names, qualification labels) — part of the
 * deferred i18n "content pass" (see CLAUDE.md). The surrounding UI chrome is
 * translated via translations.ts.
 */

// ---- Universities (in the given ranking order; HK universities first) -------
export const UNIVERSITIES: string[] = [
  "The University of Hong Kong",
  "The Chinese University of Hong Kong",
  "Hong Kong University of Science and Technology",
  "Hong Kong Polytechnic University",
  "City University of Hong Kong",
  "Hong Kong Baptist University",
  "Education University of Hong Kong",
  "Lingnan University",
  "Hong Kong Metropolitan University",
  "Hang Seng University of Hong Kong",
  "Hong Kong Shue Yan University",
  "Massachusetts Institute of Technology",
  "Imperial College London",
  "Stanford University",
  "University of Oxford",
  "Harvard University",
  "University of Cambridge",
  "California Institute of Technology",
  "ETH Zurich",
  "University College London",
  "National University of Singapore",
  "Nanyang Technological University",
  "Peking University",
  "Tsinghua University",
  "University of Pennsylvania",
  "Cornell University",
  "Yale University",
  "UNSW Sydney",
  "Johns Hopkins University",
  "University of California Berkeley",
  "École Polytechnique Fédérale de Lausanne",
  "University of Melbourne",
  "University of Chicago",
  "Technical University of Munich",
  "Fudan University",
  "Princeton University",
  "University of Sydney",
  "Australian National University",
  "McGill University",
  "Monash University",
  "University of Toronto",
  "Université Paris Sciences et Lettres",
  "University of Edinburgh",
  "Shanghai Jiao Tong University",
  "King's College London",
  "Seoul National University",
  "University of Tokyo",
  "University of Manchester",
  "University of Queensland",
  "Yonsei University",
  "Columbia University",
  "Institut Polytechnique de Paris",
  "Northwestern University",
  "University of British Columbia",
  "Zhejiang University",
  "Delft University of Technology",
  "University of California Los Angeles",
  "University of Michigan",
  "Korea University",
  "National Taiwan University",
  "Carnegie Mellon University",
  "University of Malaya",
  "University of Bristol",
  "New York University",
  "KU Leuven",
  "University of Amsterdam",
  "Ludwig Maximilian University of Munich",
  "London School of Economics and Political Science",
  "King Fahd University of Petroleum and Minerals",
  "Kyoto University",
  "Korea Advanced Institute of Science and Technology",
  "Brown University",
  "University of Auckland",
  "University of Warwick",
  "University of Birmingham",
  "Duke University",
  "Lund University",
  "University of Texas at Austin",
  "Sorbonne University",
  "University of Illinois Urbana-Champaign",
  "Trinity College Dublin",
  "Université Paris-Saclay",
  "University of Western Australia",
  "University of Leeds",
  "Adelaide University",
  "University of Glasgow",
  "University of California San Diego",
  "KTH Royal Institute of Technology",
  "University of Sheffield",
  "Universidad de Buenos Aires",
  "Durham University",
  "Heidelberg University",
  "Politecnico di Milano",
  "University of Technology Sydney",
  "Uppsala University",
  "Nanjing University",
  "University of Copenhagen",
  "Pennsylvania State University",
  "University of Washington",
  "Boston University",
  "University of Osaka",
  "University of Alberta",
  "Institute of Science Tokyo",
  "University of Nottingham",
  "Freie Universität Berlin",
  "University of Zurich",
];

// ---- Hong Kong secondary schools (in the given order) -----------------------
export const HK_SECONDARY_SCHOOLS: string[] = [
  "Belilios Public School",
  "Canossa College",
  "Caritas Chai Wan Marden Foundation Secondary School",
  "CCC Kwei Wah Shan College",
  "Cheung Chuk Shan College",
  "The Chinese Foundation Secondary School",
  "Chinese International School",
  "Chong Gene Hang College",
  "Clementi Secondary School",
  "CNEC Lau Wing Sang Secondary School",
  "Cognitio College (Hong Kong)",
  "Delia School of Canada",
  "Fortress Hill Methodist Secondary School",
  "Fukien Secondary School (Siu Sai Wan)",
  "Henrietta Secondary School",
  "Hon Wah College",
  "Hong Kong Chinese Women's Club College",
  "Hongkong Japanese School",
  "Islamic Kasim Tuet Memorial College",
  "Kellett School",
  "Kiangsu-Chekiang College North Point",
  "Lingnan Hang Yee Memorial Secondary School",
  "Lingnan Secondary School",
  "Man Kiu College",
  "Methodist Church Hong Kong Wesley College",
  "Munsang College (Hong Kong Island)",
  "Precious Blood Secondary School",
  "Pui Kiu Middle School",
  "Salesian English School",
  "Shau Kei Wan East Government Secondary School",
  "Shau Kei Wan Government Secondary School",
  "Sheng Kung Hui Li Fook Hing Secondary School",
  "St. Joan of Arc Secondary School",
  "St. Mark's School",
  "Caritas Wu Cheng Chung Secondary School",
  "Buddhist Fat Ho Memorial College",
  "Caritas Charles Vath College",
  "Cheung Chau Government Secondary School",
  "Christian Zheng Sheng College",
  "Discovery Bay International School",
  "Discovery College",
  "HKFEW Wong Cho Bau Secondary School",
  "Ho Yu College and Primary School",
  "Ling Liang Church E Wun Secondary School",
  "Po Leung Kuk Mrs. Ma Kam Ming-Cheung Fook Sien College",
  "Tung Chung Catholic School",
  "YMCA of Hong Kong Christian College",
  "American International School Hong Kong",
  "Anantara College",
  "Australian International School Hong Kong",
  "Bishop Hall Jubilee School",
  "Carmel Secondary School",
  "CCC Kei To Secondary School",
  "Chan Sui Ki (La Salle) College",
  "Christian Alliance P. C. Lau Memorial International School",
  "Diocesan Boys' School",
  "Diocesan Girls' School",
  "Heep Yunn School",
  "HKICC Lee Shau Kee School of Creativity",
  "Hoi Ping Chamber of Commerce Secondary School",
  "Holy Carpenter Secondary School",
  "Holy Family Canossian College",
  "Homantin Government Secondary School",
  "Jockey Club Government Secondary School",
  "King George V School",
  "Kingston International School",
  "Kowloon Tong School",
  "Kowloon True Light Middle School",
  "La Salle College",
  "Maryknoll Convent School",
  "Munsang College",
  "New Asia Middle School",
  "Notre Dame College",
  "Pentecostal School",
  "Po Leung Kuk Ngan Po Ling College",
  "Pooi To Middle School",
  "Pui Ching Middle School",
  "Rhenish Church Pang Hok-ko Memorial College",
  "Scientia Secondary School",
  "Sear Rogers International School",
  "Sheng Kung Hui Holy Trinity Church Secondary School",
  "Sheng Kung Hui Tsoi Kung Po Secondary School",
  "Shun Tak Fraternal Association Seaward Woo College",
  "St. Teresa Secondary School",
  "Tang King Po School",
  "Times College",
  "Tung Wah Group of Hospitals Wong Fut Nam College",
  "Wa Ying College",
  "Yew Chung International School",
  "Yu Chun Keung Memorial College",
  "YWCA Hioe Tjo Yoeng College",
  "Buddhist Sin Tak College",
  "Buddhist Yip Kei Nam Memorial College",
  "Caritas St. Joseph Secondary School",
  "Carmel Alison Lam Foundation Secondary School",
  "CCC Chuen Yuen College",
  "CCC Yenching College",
  "CNEC Christian College",
  "CNEC Lee I Yao Memorial Secondary School",
  "Cotton Spinners Association Secondary School",
  "Daughters of Mary Help of Christians Siu Ming Catholic Secondary School",
  "HKSYC & IA Chan Nam Chong Memorial College",
  "Hong Kong Taoist Association the Yuen Yuen Institute No.1 Secondary School",
  "Ju Ching Chu Secondary School (Kwai Chung)",
  "Kiangsu-Chekiang College (Kwai Chung)",
  "Kwai Chung Methodist College",
  "Lai King Catholic Secondary School",
  "Lingnan Dr. Chung Wing Kwong Memorial Secondary School",
  "Lions Clubs International Tseung Chui King College",
  "Lok Sin Tong Ku Chiu Man Secondary School",
  "Lok Sin Tong Leung Chik Wai Memorial School",
  "Methodist Lee Wai Lee College",
  "Po Leung Kuk Lo Kit Sing (1983) College",
  "Pope Paul VI College",
  "Queen's College Old Boys' Association Secondary School",
  "Salesians of Don Bosco Ng Siu Mui Secondary School",
  "Shek Lei Catholic Secondary School",
  "Sheng Kung Hui Lam Woo Memorial Secondary School",
  "Shun Tak Fraternal Association Lee Shau Kee College",
  "Tung Wah Group of Hospitals Chen Zao Men College",
  "Tung Wah Group of Hospitals Mrs. Wu York Yu Memorial College",
  "Tung Wah Group of Hospitals S. C. Gaw Memorial College",
  "Buddhist Ho Nam Kam College",
  "CCC Kei Chi Secondary School",
  "CCC Mong Man Wai College",
  "Delia Memorial School (Hip Wo)",
  "Delia Memorial School (Hip Wo No.2 College)",
  "ECF Saint Too Canaan College",
  "FDBWA Szeto Ho Secondary School",
  "Fukien Secondary School",
  "HKWMA Chu Shek Lun Secondary School",
  "Hong Kong Sheng Kung Hui Bishop Hall Secondary School",
  "Hong Kong Taoist Association Ching Chung Secondary School",
  "Ko Lui Secondary School",
  "Kwun Tong Government Secondary School",
  "Kwun Tong Kung Lok Government Secondary School",
  "Kwun Tong Lutheran College",
  "Kwun Tong Maryknoll College",
  "Leung Shek Chee College",
  "Maryknoll Secondary School",
  "Mission Covenant Church Holm Glad College",
  "Mu Kuang English School",
  "Ning Po College",
  "Ning Po No.2 College",
  "NLSI Lui Kwok Pat Fong College",
  "Po Chiu Catholic Secondary School",
  "Sheng Kung Hui Kei Hau Secondary School",
  "Sheng Kung Hui Leung Kwai Yee Secondary School",
  "Shun Lee Catholic Secondary School",
  "Sing Yin Secondary School",
  "St. Antonius Girls' College",
  "St. Catharine's School for Girls",
  "St. Joseph's Anglo-Chinese School",
  "St. Paul's School (Lam Tin)",
  "United Christian College (Kowloon East)",
  "Yan Chai Hospital Law Chan Chor Si College",
  "Caritas Fanling Chan Chun Ha Secondary School",
  "CCC Kei San Secondary School",
  "Christian Alliance S. W. Chan Memorial College",
  "De La Salle Secondary School N.T.",
  "Elegantia College",
  "Fanling Government Secondary School",
  "Fanling Kau Yan College",
  "Fanling Lutheran Secondary School",
  "Fanling Rhenish Church Secondary School",
  "Fung Kai Liu Man Shek Tong Secondary School",
  "Fung Kai No.1 Secondary School",
  "HHCKLA Buddhist Ma Kam Chan Memorial English Secondary School",
  "Hong Kong Taoist Association Tang Hin Memorial Secondary School",
  "International College Hong Kong",
  "Po Leung Kuk Ma Kam Ming College",
  "Sheng Kung Hui Chan Young Secondary School",
  "Sheung Shui Government Secondary School",
  "St. Francis of Assisi's College",
  "Tin Ka Ping Secondary School",
  "Tung Wah Group of Hospitals Kap Yan Directors' College",
  "Tung Wah Group of Hospitals Li Ka Shing College",
  "Carmel Divine Grace Foundation Secondary School",
  "Catholic Ming Yuen Secondary School",
  "Cheng Chek Chee Secondary School",
  "Christian and Missionary Alliance Sun Kei Secondary School",
  "Creative Secondary School",
  "Evangel College",
  "G. T. (Ellen Yeung) College",
  "Heung To Secondary School (Tseung Kwan O)",
  "HHCKLA Buddhist Ching Kok Secondary School",
  "Hong Kong Chinese Christian Churches Union Logos Academy",
  "Hong Kong Adventist Academy",
  "Hong Kong and Macau Lutheran Church Queen Maud Secondary School",
  "Hong Kong Taoist Association the Yuen Yuen Institute No.3 Secondary School",
  "King Ling College",
  "MKMCF Ma Chan Duen Hey Memorial College",
  "Po Kok Secondary School",
  "Po Leung Kuk Ho Yuk Ching (1984) College",
  "Po Leung Kuk Laws Foundation College",
  "Pok Oi Hospital 80th Anniversary Tang Ying Hei College",
  "Man Kwan QualiEd College",
  "Sai Kung Sung Tsun Catholic School",
  "Shun Tak Fraternal Association Cheng Yu Tung Secondary School",
  "Tseung Kwan O Government Secondary School",
  "Tung Wah Group of Hospitals Lui Yun Choy Memorial College",
  "Wellington Education Organization Chang Pui Chung Memorial School",
  "Yan Chai Hospital Lan Chi Pat Memorial Secondary School",
  "Yan Chai Hospital Wong Wha San Secondary School",
  "Renaissance College",
  "Baptist Lui Ming Choi Secondary School",
  "Buddhist Kok Kwong Secondary School",
  "Buddhist Wong Wan Tin College",
  "Caritas Ma On Shan Secondary School",
  "Chinese YMCA College",
  "Chiu Chow Association Secondary School",
  "Christ College",
  "Christian Alliance Cheng Wing Gee College",
  "CUHKFAA Chan Chun Ha Secondary School",
  "GCC & ITKD Lau Pak Lok Secondary School",
  "Helen Liang Memorial Secondary School (Shatin)",
  "HKBUAS Wong Kam Fai Secondary and Primary School",
  "Hong Kong and Kowloon CCPA Ma Chung Sum Secondary School",
  "Hong Kong Chinese Women's Club Fung Yiu King Memorial Secondary School",
  "Immaculate Heart of Mary College",
  "International Christian School",
  "Jockey Club Ti–I College",
  "Kiangsu-Chekiang College (Shatin)",
  "Kwok Tak Seng Catholic Secondary School",
  "Lam Tai Fai College",
  "Li Po Chun United World College of Hong Kong",
  "Lock Tao Secondary School",
  "Lok Sin Tong Young Ko Hsiao Lin Secondary School",
  "Ma On Shan St. Joseph's Secondary School",
  "Ma On Shan Tsung Tsin Secondary School",
  "Ng Yuk Secondary School",
  "Pentecostal Lam Hon Kwong School",
  "Po Leung Kuk C. W. Chu College",
  "Po Leung Kuk Wu Chung College",
  "Pok Oi Hospital Chan Kai Memorial College",
  "Pui Kiu College",
  "Sha Tin Government Secondary School",
  "Sha Tin Methodist College",
  "Shatin College",
  "Shatin Pui Ying College",
  "Shatin Tsung Tsin Secondary School",
  "Sheng Kung Hui Lam Kau Mow Secondary School",
  "Sheng Kung Hui Tsang Shiu Tim Secondary School",
  "St. Rose of Lima's College",
  "Stewards Pooi Kei College",
  "Tak Sun Secondary School",
  "Toi Shan Association College",
  "Tsang Pik Shan (Sung Lan) Secondary School",
  "Tung Wah Group of Hospitals Mrs. Fung Wong Fung Ting College",
  "Tung Wah Group of Hospitals Wong Fung Ling College",
  "Tung Wah Group of Hospitals Yow Kam Yuen College",
  "Yan Chai Hospital Tung Chi Ying Memorial Secondary School",
  "Buddhist Tai Hung College",
  "CCC Ming Yin College",
  "Cheung Sha Wan Catholic Secondary School",
  "China Holiness College",
  "CMA Secondary School",
  "Concordia International School",
  "Concordia Lutheran School (Hong Kong)",
  "Delia Memorial School (Broadway)",
  "Delia Memorial School (Glee Path)",
  "Heung To Middle School",
  "HKSYC & IA Wong Tai Shan Memorial College",
  "Holy Trinity College",
  "Kowloon Technical School",
  "Maria College",
  "Maryknoll Fathers' School",
  "Nam Wah Catholic Secondary School",
  "Our Lady of the Rosary College",
  "Po Leung Kuk Choi Kai Yau School",
  "Po Leung Kuk Vicwood K.T. Chong Sixth Form College",
  "Po Leung Kuk Tong Nai Kan Junior Secondary College",
  "Sheng Kung Hui St. Mary's Church Mok Hing Yiu College",
  "St. Margaret's Co-educational English Secondary and Primary School",
  "Tack Ching Girls' Secondary School",
  "Tak Nga Secondary School",
  "Tsung Tsin Christian Academy",
  "Tsung Tsin Middle School",
  "Tung Wah Group of Hospitals Chang Ming Thien College",
  "United Christian College",
  "Wai Kiu College",
  "Ying Wa College",
  "Aberdeen Baptist Lui Ming Choi College",
  "Aberdeen Technical School",
  "Canadian International School of Hong Kong",
  "Caritas Chong Yuet Ming Secondary School",
  "German Swiss International School",
  "Hong Kong International School",
  "Hong Kong Sea School",
  "Hong Kong True Light College",
  "Hong Kong University Graduate Association College",
  "Independent Schools Foundation Academy",
  "Po Leung Kuk Wai Yin College",
  "Pui Tak Canossian College",
  "Pui Ying Secondary School",
  "Sacred Heart Canossian College",
  "San Wui Commercial Society Chan Pak Sha School",
  "Sheng Kung Hui Lui Ming Choi Secondary School",
  "Singapore International School",
  "South Island School",
  "St. Peter's Secondary School",
  "St. Stephen's College",
  "Victoria Shanghai Academy",
  "West Island School",
  "Yu Chun Keung Memorial College No.2",
  "Assembly of God Hebron Secondary School",
  "Buddhist Tai Kwong Chi Hong College",
  "Carmel Holy Word Secondary School",
  "Carmel Pak U Secondary School",
  "CCC Fung Leung Kit Memorial Secondary School",
  "China Holiness Church Living Spirit College",
  "Confucian Ho Kwok Pui Chun College",
  "Hong Kong and Kowloon Kaifong Women's Association Sun Fong Chung College",
  "Hong Kong Red Swastika Society Tai Po Secondary School",
  "Hong Kong Taoist Association The Yuen Yuen Institute No.2 Secondary School",
  "Hong Kong Teachers' Association Lee Heng Kwei Secondary School",
  "Kau Yan College",
  "Law Ting Pong Secondary School",
  "Ling Liang Church M. H. Lau Secondary School",
  "New Territories Heung Yee Kuk Tai Po District Secondary School",
  "SALEM-Immanuel Lutheran College",
  "Sheng Kung Hui Bishop Mok Sau Tseng Secondary School",
  "Tai Po Sam Yuk Secondary School",
  "Valtorta College",
  "Wong Shiu Chi Secondary School",
  "AD & FD POHL Leung Sing Tak College",
  "Ho Fung College",
  "Liu Po Shan Memorial College",
  "Lui Ming Choi Lutheran College",
  "Po Leung Kuk Lee Shing Pik College",
  "Po Leung Kuk Yao Ling Sun College",
  "Po on Commercial Association Wong Siu Ching Secondary School",
  "Sheng Kung Hui Li Ping Secondary School",
  "St. Francis Xavier's School Tsuen Wan",
  "Textile Institute American Chamber of Commerce Woo Hon Fai Secondary School",
  "Tsuen Wan Government Secondary School",
  "Tsuen Wan Public Ho Chuen Yiu Memorial College",
  "Yan Chai Hospital Lim Por Yen Secondary School",
  "Baptist Wing Lung Secondary School",
  "Buddhist Sum Heung Lam Memorial College",
  "Caritas Tuen Mun Marden Foundation Secondary School",
  "Carmel Bunnan Tong Memorial Secondary School",
  "CCC Hoh Fuk Tong College",
  "CCC Tam Lee Lai Fun Memorial Secondary School",
  "Ching Chung Hau Po Woon Secondary School",
  "Christian Alliance College",
  "Christian Alliance S. C. Chan Memorial College",
  "Chung Sing Benevolent Society Mrs. Aw Boon Haw Secondary School",
  "CMA Choi Cheung Kok Secondary School",
  "Harrow International School Hong Kong",
  "HHCKLA Buddhist Leung Chik Wai College",
  "Ho Ngai College",
  "Ju Ching Chu Secondary School (Tuen Mun)",
  "Lui Cheung Kwong Lutheran College",
  "Madam Lau Kam Lung Secondary School of Miu Fat Buddhist Monastery",
  "NLSI Peace Evangelical Secondary School",
  "PAOC Ka Chi Secondary School",
  "Po Leung Kuk Centenary Li Shiu Chung Memorial College",
  "Po Leung Kuk Tang Yuk Tien College",
  "San Wui Commercial Society Secondary School",
  "Semple Memorial Secondary School",
  "Sheng Kung Hui St. Simon's Lui Ming Choi Secondary School",
  "Shi Hui Wen Secondary School",
  "Shun Tak Fraternal Association Leung Kau Kui College",
  "Shun Tak Fraternal Association Tam Pak Yu College",
  "South Tuen Mun Government Secondary School",
  "Stewards MKMCF Ma Ko Pan Memorial College",
  "Tsung Tsin College",
  "Tuen Mun Catholic Secondary School",
  "Tuen Mun Government Secondary School",
  "Tung Wah Group of Hospitals Sun Hoi Directors' College",
  "Tung Wah Group of Hospitals Yau Tze Tin Memorial College",
  "Yan Chai Hospital No.2 Secondary School",
  "Yan Oi Tong Chan Wong Suk Fong Memorial Secondary School",
  "Yan Oi Tong Tin Ka Ping Secondary School",
  "YPI & CA Lee Lim Ming College",
  "Buddhist Wong Fung Ling College",
  "CCC Kung Lee College",
  "Concordia Lutheran School - North Point",
  "Confucius Hall Middle School",
  "Hong Kong Tang King Po College",
  "Hotung Secondary School",
  "Island School",
  "Lycée Français International Victor Segalen",
  "Marymount Secondary School",
  "Queen's College",
  "Rosaryhill School",
  "Sheng Kung Hui Tang Shiu Kin Secondary School",
  "St. Francis' Canossian College",
  "St. Paul's Convent School",
  "St. Paul's Secondary School",
  "Tang Shiu Kin Victoria Government Secondary School",
  "True Light Middle School of Hong Kong",
  "Tung Wah Group of Hospitals Lee Ching Dea Memorial College",
  "Wah Yan College Hong Kong",
  "Assembly of God Morrison College",
  "Buddhist Hung Sean Chau Memorial College",
  "CCC Heep Woh College",
  "CCC Kei Heep Secondary School",
  "CCC Rotary Secondary School",
  "Choi Hung Estate Catholic Secondary School",
  "Cognitio College (Kowloon)",
  "Good Hope School",
  "Ho Lap College",
  "International Christian Quality Music Secondary and Primary School",
  "Kit Sam Lam Bing Yim Secondary School",
  "Lee Kau Yan Memorial School",
  "Lok Sin Tong Wong Chung Ming Secondary School",
  "Lok Sin Tong Yu Kan Hing Secondary School",
  "Lung Cheung Government Secondary School",
  "Ng Wah Catholic Secondary School",
  "Our Lady's College",
  "PHC Wing Kwong College",
  "Po Leung Kuk Celine Ho Yam Tong College",
  "Po Leung Kuk No.1 W. H. Cheung College",
  "Salvation Army William Booth Secondary School",
  "Sheng Kung Hui St. Benedict's School",
  "St. Bonaventure College and High School",
  "Stewards Pooi Tun Secondary School",
  "Tak Oi Secondary School",
  "CCC Ming Kei College",
  "ELCHK Lutheran Secondary School",
  "Hong Kong and Kowloon Chiu Chow Public Association Secondary School",
  "HKMA David Li Kwok Po College",
  "Kowloon Sam Yuk Secondary School",
  "Lai Chack Middle School",
  "Lung Kong World Federation School Limited Lau Wong Fat Secondary School",
  "Methodist College (Kowloon)",
  "Newman Catholic College",
  "Queen Elizabeth School",
  "Sheng Kung Hui All Saints' Middle School",
  "Sir Ellis Kadoorie Secondary School (West Kowloon)",
  "St. Francis Xavier's College Tai Kok Tsui",
  "St. Mary's Canossian College",
  "True Light Girls' College",
  "Wah Yan College Kowloon",
  "Bethel High School",
  "Buddhist Mau Fung Memorial College",
  "Caritas Yuen Long Chan Chun Ha Secondary School",
  "CCC Fong Yun Wah Secondary School",
  "CCC Kei Long College",
  "CCC Kei Yuen College",
  "Chinese YMCA Secondary School",
  "Chiu Lut Sau Memorial Secondary School",
  "CUHKFAA Thomas Cheung Secondary School",
  "Cumberland Presbyterian Church Yao Dao Secondary School",
  "ELCHK Lutheran Academy",
  "ELCHK Yuen Long Lutheran College",
  "ELCHK Yuen Long Lutheran Secondary School",
  "Gertrude Simon Lutheran College",
  "Heung To Middle School (Tin Shui Wai)",
  "Ho Dao College",
  "Hong Kong Federation of Youth Groups Lee Shau Kee College",
  "Hong Kong Management Association K. S. Lo College",
  "Jockey Club Eduyoung College",
  "Ju Ching Chu Secondary School (Yuen Long)",
  "New Territories Heung Yee Kuk Yuen Long District Secondary School",
  "Pak Kau College",
  "Pok Oi Hospital Tang Pui King Memorial College",
  "Pui Shing Catholic Secondary School",
  "Queen Elizabeth School Old Students' Association Secondary School",
  "Queen Elizabeth School Old Students' Association Tong Kwok Wah Secondary School",
  "Shap Pat Heung Rural Committee Kung Yik She Secondary School",
  "Sheng Kung Hui Bishop Baker Secondary School",
  "Shun Tak Fraternal Association Yung Yau College",
  "Shung Tak Catholic English College",
  "Tin Shui Wai Government Secondary School",
  "Tin Shui Wai Methodist College",
  "Tung Wah Group of Hospitals C. Y. Ma Memorial College",
  "Tung Wah Group of Hospitals Kwok Yat Wai College",
  "Tung Wah Group of Hospitals Lo Kon Ting Memorial College",
  "YLPMSAA Tang Siu Tong Secondary School",
  "Yuen Long Catholic Secondary School",
  "Yuen Long Merchants Association Secondary School",
  "Yuen Long Public Secondary School",
  "Yuen Yuen Institute MFBM Nei Ming Chan Lui Chung Tak Memorial College",
  "Buddhist Chi Hong Chi Lin Memorial College",
  "Buddhist Hui Yuan College",
  "Buddhist Tai Kwong Secondary School",
  "Buddhist Wai Yan Memorial College",
  "Caritas Magdalene School",
  "Caritas Shatin Marden Foundation Secondary School",
  "Chan Shu Kui Memorial School",
  "Chung Wah Middle School",
  "Delia Memorial School (Yuet Wah)",
  "Delia Memorial School (Taikoo Shing)",
  "Delia Memorial School (Tsuen Wan)",
  "Ha Kwai Chung Government Secondary School",
  "Hang Seng School of Commerce",
  "Hong Kong and Kowloon Chiu Chow Public Association Ma Chung Sum Secondary School",
  "Hong Kong Rennie's Mill School",
  "Hong Kong Sam Yuk Secondary School",
  "New Territories Heung Yee Kuk Southern District Secondary School",
  "Royal Hong Kong Police Cadet School",
  "Sam Yuk Middle School",
  "Sha Tau Kok Government Secondary School",
  "Sheung Kwai Chung Government Secondary School",
  "Sir Ellis Kadoorie Secondary School (Shatin)",
  "St Margaret's College",
  "St. Margaret Girls' College Hong Kong",
  "Sung Lan Middle School",
  "Tai Po Government Secondary School",
  "The Amoy College",
  "Tsuen Wan Government Secondary Technical School",
  "Wellington College",
  "Yan Chai Hospital No. 5 Secondary School",
];

// ---- Secondary qualifications (reuses the app's academic exam set) -----------
export const SECONDARY_QUALIFICATIONS: string[] = [
  "DSE",
  "IB",
  "IGCSE",
  "A-Level",
  "AP",
  "HSC",
  "Gaokao",
  "Other",
];

// Score scales per qualification. Qualifications NOT listed here (AP, HSC,
// Gaokao, Other) have no fixed scale — their score field falls back to free text.
const range = (from: number, to: number) =>
  Array.from({ length: from - to + 1 }, (_, i) => String(from - i));

const IB_SCORES = [...range(45, 24), "Below 24"];
const DSE_BEST5 = [...range(35, 20), "Below 20"];
const IGCSE_SCORES = Array.from({ length: 12 }, (_, i) => `${12 - i} A*/A`);

// A-Level: every 3-grade combination (descending), best first (A*A*A* … EEE).
const AL_GRADES = ["A*", "A", "B", "C", "D", "E"];
const A_LEVEL_SCORES: string[] = (() => {
  const out: string[] = [];
  for (let i = 0; i < AL_GRADES.length; i++)
    for (let j = i; j < AL_GRADES.length; j++)
      for (let k = j; k < AL_GRADES.length; k++)
        out.push(AL_GRADES[i] + AL_GRADES[j] + AL_GRADES[k]);
  return out;
})();

export const SECONDARY_SCORE_OPTIONS: Record<string, string[]> = {
  DSE: DSE_BEST5,
  IB: IB_SCORES,
  IGCSE: IGCSE_SCORES,
  "A-Level": A_LEVEL_SCORES,
};

// ---- University degree + result ---------------------------------------------
export const UNI_DEGREES: string[] = [
  "Higher Diploma",
  "Associate Degree",
  "Bachelor's Degree",
  "Postgraduate Diploma",
  "Master's Degree",
  "MPhil",
  "PhD / Doctorate",
  "Other",
];

export const UNI_HONOURS: string[] = [
  "First Class Honours",
  "Upper Second Class (2:1)",
  "Lower Second Class (2:2)",
  "Third Class Honours",
  "Distinction",
  "Merit",
  "Pass",
  "Summa Cum Laude",
  "Magna Cum Laude",
  "Cum Laude",
  "Other",
];
